### ISSUE TITLE
[Bug Report]Clash 托管配置 URL

### ISSUE THREAD

**Issue by passcheng** [SukkaW/Koolshare-Clash#13]
Clash 托管配置 URL 不支持带&符号链接

**Comment by SukkaW** [comment]
请提供更多修详细信息，如该订阅链接中的 `&` 在 URL 中的配置；并对 不支持 这一行为提供更多信息，如插件返回的提示信息、dbus 中保存的数据和提交的数据不符等等。
由于不能提供任何有效信息，这条 issue 将会被关闭并锁定。
