### ISSUE TITLE
有适配merlin的计划嘛

### ISSUE THREAD

**Issue by Ryziii** [SukkaW/Koolshare-Clash#22]
RT

**Comment by SukkaW** [comment]
有相关计划，拟定取名 ClashM。但是在期待 Clash on Merlin 之前，你需要知道：

- 路由器的性能非常有限
- Clash 需要至少 15MB 的存储空间才能正常运行
- 在我拥有测试设备之前 ClashM 的开发不会开始
- 我不会为了单纯为了 Merlin 去买个新的路由器——OpenWRT 的 R3G 做 AP 我用得很舒服
- 不接受任何众筹或者捐赠——这是在强迫我做出成品

**Comment by Kazeta-chinu** [comment]
后续hnd/axhnd平台的机器有希望吗。。没有梅林的小伙伴很伤心

**Comment by laincat** [comment]
(原版 Openwrt 会考虑嘛？某大大的版本，功能和完善程度都太低了。。。)

**Comment by Comah** [comment]
梅林其实也挺好用 就是缺少很多插件 例如 clash啦   希望大大有空考虑玩一下梅林 弄个洋垃圾6300v2便可。

**Comment by SukkaW** [comment]
@Comah 

https://github.com/SukkaW/Koolshare-Clash/issues/22#issuecomment-487102585

> * 在我拥有测试设备之前 ClashM 的开发不会开始

> * 我不会为了单纯为了 Merlin 去买个新的路由器——OpenWRT 的 R3G 做 AP 我用得很舒服

> * 不接受任何众筹或者捐赠——这是在强迫我做出成品

**Comment by Comah** [comment]
> @Comah
> 
> [#22 (comment)](https://github.com/SukkaW/Koolshare-Clash/issues/22#issuecomment-487102585)
> 
> > * 在我拥有测试设备之前 ClashM 的开发不会开始
> 
> > * 我不会为了单纯为了 Merlin 去买个新的路由器——OpenWRT 的 R3G 做 AP 我用得很舒服
> 
> > * 不接受任何众筹或者捐赠——这是在强迫我做出成品
完全明白！辛苦大佬了！

**Comment by flyhigherpi** [comment]
> 梅林其实也挺好用 就是缺少很多插件 例如 clash啦 希望大大有空考虑玩一下梅林 弄个洋垃圾6300v2便可。

大半夜瞧我看到了啥。

> 梅林其实也挺好用 就是缺少很多插件 例如 clash啦 希望大大有空考虑玩一下梅林 弄个洋垃圾6300v2便可。

大半夜瞧我搜到了啥。对380喊不

**Comment by Comah** [comment]
> 大半夜瞧我搜到了啥。对380喊不
现在6300v2也能刷384了 也能组aimesh了
