### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by cjaySu** [SukkaW/Koolshare-Clash#26]
**Bug 详情**

**你的操作**

下载安装完后，点击提示链接丢失

**屏幕截图**
![image](https://user-images.githubusercontent.com/20206112/57519242-6115b780-734d-11e9-90a8-0a90175a008d.png)

**调试信息**

```
```

**Comment by cjaySu** [comment]
![image](https://user-images.githubusercontent.com/20206112/57519294-7f7bb300-734d-11e9-8e9f-f78434d7a96b.png)

**Comment by SukkaW** [comment]
KoolClash 仅适用于 Koolshare OpenWRT/LEDE x86_64，请仔细阅读 README。

**Comment by ann61c** [comment]
连接丢失我也经常遇到，习以为常了.... Openwrt
