### ISSUE TITLE
[Feature Request]希望提高“指定主机操作（局域网内设备的放行、通过）”功能的开发优先度

### ISSUE THREAD

**Issue by redcray** [SukkaW/Koolshare-Clash#30]
如题，希望能提高“指定主机操作（局域网内设备的放行、通过）”功能的开发优先度。
一般能用上软路由的人都会有下载机（BT）之类的，希望能确保直通。

在最近的beta版的访问控制取消了常用端口设置，测试发现不能过滤BT流量了。

**Comment by SukkaW** [comment]
恰恰相反，由于使用 `fake-ip` 功能，使用 iptables 进行流量控制已经毫无意义。
建议将 KoolClash 安装在旁路网关，或者使用 Clash 配置文件编写分流规则。
