### ISSUE TITLE
[Bug Report]更新GeoIP后，不能显示数据库版本

### ISSUE THREAD

**Issue by Allentong61** [SukkaW/Koolshare-Clash#34]
**Bug 详情**
成功更新GeoIP后，当前 IP 数据库版本没有获取到版本信息。
不知是显示上的bug，还是更新后数据库不能用了

**你的操作**
点击更新IP数据库，显示如下

**屏幕截图**
--操作日志
【2019年06月03日 07:03:54】: 开始下载最新 IP 数据库...
【2019年06月03日 07:03:59】: 下载完成，开始解压
【2019年06月03日 07:03:59】: 更新 IP 数据库至  版本
【2019年06月03日 07:03:59】: 清理临时文件...
【2019年06月03日 07:03:59】: IP 数据库更新完成！

--附加功能
当前 IP 数据库版本    没有获取到版本信息
![批注 2019-06-03 070831](https://user-images.githubusercontent.com/45547129/58768487-a5077f80-85ce-11e9-84dc-ffd98c2fb025.png)

**调试信息**
======================== KoolClash 调试工具 ========================
调试信息生成于 Mon Jun 03 2019 07:07:05 GMT+0800 (香港标准时间)
当前浏览器：Chrome 74
-------------------- Koolshare OpenWrt 基本信息 --------------------
固件版本： Openwrt Koolshare mod V2.31, r10822-50aa0525d1 by fw867
路由器 LAN IP：
------------------------ KoolClash 基本信息 ------------------------
KoolClash 版本：0.17.4-beta
Clash 核心版本：Clash v0.14.0-7-g89168e6 linux amd64 Sat 18 May 2019 05:35:13 PM UTC
KoolClash 当前状态：Clash 进程正在运行
用户指定 Clash 外部控制 Host：未改动
IP 数据库是否存在：true
-------------------------- Clash 进程信息 --------------------------
20569 root      114m S    /koolshare/bin/clash -d /koolshare/koolclash/config/
22741 root      1080 S    /bin/sh /koolshare/scripts/koolclash_debug.sh 433865
22831 root      1080 S    /bin/sh /koolshare/scripts/koolclash_debug.sh 433865

------------------------ Clash 配置文件信息 ------------------------
Clash 原始配置文件是否存在：true
Clash 运行配置文件是否存在：true
Clash 透明代理端口：23456
Clash 是否允许局域网连接：true
Clash 外部控制监听地址：:6170
--------------------- Clash 配置文件 DNS 配置 ----------------------
Clash DNS 是否启用：true
Clash DNS 解析 IPv6：false
Clash DNS 增强模式：fake-ip
Clash DNS 监听：0.0.0.0:23453
KoolClash 当前 DNS 模式：4
-------------------- KoolClash 自定义 DNS 配置 ---------------------

------------------------- iptables 条目 ---------------------------
 * iptables mangle 中 Clash 相关条目

 * iptables nat 中 Clash 相关条目
    0     0 koolclash_dns  tcp  --  *      *       0.0.0.0/0            198.19.0.0/24        tcp dpt:53
    0     0 koolclash_dns  udp  --  *      *       0.0.0.0/0            198.19.0.0/24        udp dpt:53
   77  4004 koolclash  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           

 * iptables mangle 中 koolclash 链

 * iptables nat 中 koolclash 链
   77  4004 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set koolclash_white dst
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            redir ports 23456

* iptables mangle 中 koolclash_dns 链

 * iptables nat 中 koolclash_dns 链
    0     0 DNAT       udp  --  *      *       0.0.0.0/0            198.19.0.0/24        udp dpt:53 to::23453
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            198.19.0.0/24        tcp dpt:53 to::23453

 * iptables nat 中 Chromecast 相关条目
4        0     0 koolclash_dns  tcp  --  *      *       0.0.0.0/0            198.19.0.0/24        tcp dpt:53
5        0     0 koolclash_dns  udp  --  *      *       0.0.0.0/0            198.19.0.0/24        udp dpt:53

---------------------- ipset 白名单 IP 列表 ------------------------
Name: koolclash_white
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 920
References: 1
Number of entries: 9
Members:
240.0.0.0/4
10.0.0.0/8
224.0.0.0/4
100.64.0.0/10
127.0.0.0/8
172.16.0.0/12
192.168.0.0/16
169.254.0.0/16
0.0.0.0/8

===================================================================

**Comment by SukkaW** [comment]
KoolClash 对下载是否成功的判断可能存在问题，或者 MaxMind 更新了文件名规则。
