### ISSUE TITLE
强烈建议恢复Clash直接接管DNS选项

### ISSUE THREAD

**Issue by lesliedu** [SukkaW/Koolshare-Clash#35]
建议所有的请求有Clash直接处理，设置路由器的网关和DNS IP太麻烦，绝大多数的都是在主路由器上用来科学上网的，，，，

**Comment by SukkaW** [comment]
KoolClash 从 `0.17.0` 版本开始，必须在旁路网关设备上以 `fake-ip` 模式运行。
使用 `redir-host` 模式将会导致一系列严重影响网络体验的后果，包括但不限于 HTTP 延时增大、DNS 污染、Chrome 浏览器无法访问某些网站等。如果坚持在主路由上运行 KoolClash，请自行降级到早于 `0.17.0` 的版本。
KoolClash 不对使用者的任何损失负责，包括但不限于 Kernel Panic、设备无法开机或正常使用、硬盘损坏或数据丢失、原子弹爆炸、第三次世界大战、SCP 基金会无法阻止全球发生的 CK 级现实重构等。
