### ISSUE TITLE
请问路由器开启Clash后，局域网内某台设备如何不走Clash？

### ISSUE THREAD

**Issue by tonyzhou777** [SukkaW/Koolshare-Clash#37]
请问路由器开启Clash后，局域网内某台设备如何不走Clash？
请问如何设置？还是说Clash必须是全局代理，然后Clash内部分流？

**Comment by SukkaW** [comment]
KoolClash 自 0.17.0 版本开始必须以旁路网关模式运行。你只需要指定设备不使用安装了 KoolClash 的旁路网关即可使该设备的流量不经过 Clash。

针对早于 KoolClash 0.17.0 版本，KoolClash 支持在主路由或者旁路网关运行，局域网内设备管理需要通过修改 Clash 配置文件实现，需要用到 `SRC IPDR` `SRC PORT` 等。

**Comment by hackenfu** [comment]
SukkaW，隔壁frainzy1477最新版增加了这个功能，请问您会考虑未来加上吗？
Added Proxy Lan IP / Bypass Lan IP
Disabled to allow all Lan IP trafficgo through Proxy(Clash Client)
Proxy Lan IP(Client IP) that go through Proxy
Bypass Lan IP(Client IP) that can't go through Proxy
增加走代理的局域网IP / 不走代理的局域网IP
关闭，全局域网IP流量都走代理(Clash客户端)
设置 -> 走代理的局域网IP -> 走代理局域网IP列表 (除了选择局域网IP，其他局域网IP不走代理）
设置 -> 不走代理的局域网IP -> 不走代理局域网IP列表 (除了选择局域网IP，其他局域网IP走代理）

**Comment by SukkaW** [comment]
不会

**Comment by SukkaW** [comment]
我觉得我的介绍说的很清楚了。

> KoolClash 自 0.17.0 版本开始必须以旁路网关模式运行。你只需要指定设备不使用安装了 KoolClash 的旁路网关即可使该设备的流量不经过 Clash。
> 针对早于 KoolClash 0.17.0 版本，KoolClash 支持在主路由或者旁路网关运行，局域网内设备管理需要通过修改 Clash 配置文件实现，需要用到 SRC IPDR SRC PORT 等。

**Comment by tonyzhou777** [comment]
好的谢谢
