### ISSUE TITLE
[Bug Report] 通过 ssh 进行 git clone 失效

### ISSUE THREAD

**Issue by freeznet** [SukkaW/Koolshare-Clash#38]
**Bug 详情**

配置 fake-ip 后 通过 ssh + git clone 会无法连接，大概调试了下，感觉和 https://github.com/SukkaW/Koolshare-Clash/blob/master/koolclash/scripts/koolclash_control.sh#L307 这个iptables rule有关 没有顺利转发 fake-ip 的 22 端口连接

**你的操作**

**屏幕截图**

**调试信息**

```
```

**Comment by SukkaW** [comment]
放行 22 是 KoolClash 的 iptables 的全局设定，目的是当 Koolshare OpenWRT 失联时用于急救；
仅仅只对 Fake IP 转发 22 没用，如果直接使用 IP 进行 SSH 将不经过 Fake IP 逻辑。

**Comment by freeznet** [comment]
> 放行 22 是 KoolClash 的 iptables 的全局设定，目的是当 Koolshare OpenWRT 失联时用于急救；
> 仅仅只对 Fake IP 转发 22 没用，如果直接使用 IP 进行 SSH 将不经过 Fake IP 逻辑。

遇到的问题主要就是针对 fake-ip 解析域名到 198 ip 段，但是对应的 22 通信却没有正确转发到透明代理上，导致通过域名进行 ssh、或者通过域名进行 git + ssh 等操作失败。非 198 ip 段的 22 端口可以正常放行。
