### ISSUE TITLE
[Question] 请问进阶使用里的smart dns配置之后，如果验证clash已经正确导流到smart dns？

### ISSUE THREAD

**Issue by xiaomingplus** [SukkaW/Koolshare-Clash#41]
因为clash这里用里fake dns，所以本地貌似没法验证啊。

**Comment by xiaomingplus** [comment]
另外，有个小建议不知道可行不，就是加一个clash异常退出的日志？有的时候假死，不知道是哪个进程出了问题。

**Comment by SukkaW** [comment]
如果用 dig，可以使用 @ 参数指定使用的 DNS，-p 参数可以指定端口（SmartDNS 的默认端口是 6053）。
SmartDNS 的特征是不论如何解析结果只返回一个最快的 IP。
