### ISSUE TITLE
[Bug Report]部署在旁路由上，部分pc无法使用dns服务

### ISSUE THREAD

**Issue by NV3S** [SukkaW/Koolshare-Clash#46]
**Bug 详情**

环境：
光猫--ESXi（ikuai主路由+koolshare lede旁路由）---无线AP

作为主路由，在ikuai中配置了DHCP分发lede的地址为子设备网关，198.19.0.1/198.19.0.2为dns；
旁路由中，lede的clash配置了fake-ip（把ikuai的ip设置为自己的网关）。
见图。

网内设备有iPhone、switch、智能电视以及两台笔记本。
除了笔记本以外，包括智能电视在内的设备都能访问预期的网站和应用。
但**笔记本**打开任何网站，都会提示dns无法解析的问题（更换过浏览器）

**你的操作**

查看笔记本的ip，为自动获取，dns为198.19.0.1/198.19.0.2，网关为198.168.100.100，符合预期。
通过nslookup查询，dns能够解析成fake-ip。
如果把ip手工设置成运营商或者其他ip（119.29.29.29之类），网页和应用能够正常使用。

**屏幕截图**

![a2](https://user-images.githubusercontent.com/17755534/61342585-43992880-a87d-11e9-811d-984489989f27.png)
![a3](https://user-images.githubusercontent.com/17755534/61342586-4431bf00-a87d-11e9-84ce-1c8f3b761d3b.png)
![a1](https://user-images.githubusercontent.com/17755534/61342588-4431bf00-a87d-11e9-9b31-9e4bd0dbc755.png)

**调试信息**

======================== KoolClash 调试工具 ========================
调试信息生成于 Wed Jul 17 2019 10:24:44 GMT+0800 (中国标准时间)
当前浏览器：Chrome 75
-------------------- Koolshare OpenWrt 基本信息 --------------------
固件版本： Openwrt Koolshare mod V2.31, r10822-50aa0525d1 by fw867
路由器 LAN IP：192.168.100.100
------------------------ KoolClash 基本信息 ------------------------
KoolClash 版本：0.17.5-beta
Clash 核心版本：Clash v0.15.0-2-g7c6c147 linux amd64 Thu 11 Jul 2019 01:24:28 PM UTC
KoolClash 当前状态：Clash 进程正在运行
用户指定 Clash 外部控制 Host：192.168.100.100
-------------------------- Clash 进程信息 --------------------------
24381 root      1080 S    /bin/sh /koolshare/scripts/koolclash_debug.sh 177727
24471 root      1080 S    /bin/sh /koolshare/scripts/koolclash_debug.sh 177727
27143 root      116m S    /koolshare/bin/clash -d /koolshare/koolclash/config/

------------------------ Clash 配置文件目录 ------------------------
-rw-r--r--    1 root     root        3.7M Jul 15 07:05 Country.mmdb
-rw-r--r--    1 root     root           0 Jul 15 00:14 config.yaml
-rw-r--r--    1 root     root       52.3K Jul 15 07:01 config.yml
-rw-r--r--    1 root     root         155 Jul 17 10:25 dns.yml
-rw-r--r--    1 root     root       52.1K Jul 15 06:53 origin.yml

------------------------ Clash 配置文件信息 ------------------------
Clash 透明代理端口：23456
Clash 是否允许局域网连接：true
Clash 外部控制监听地址：192.168.100.100:6170
--------------------- Clash 配置文件 DNS 配置 ----------------------
Clash DNS 是否启用：true
Clash DNS 解析 IPv6：false
Clash DNS 增强模式：fake-ip
Clash DNS 监听：0.0.0.0:23453
KoolClash 当前 DNS 模式：4
-------------------- KoolClash 自定义 DNS 配置 ---------------------
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 119.28.28.28
    - 119.29.29.29
    - 114.114.114.114

------------------------- iptables 条目 ---------------------------
 * iptables mangle 中 Clash 相关条目

 * iptables nat 中 Clash 相关条目
    0     0 koolclash_dns  tcp  --  *      *       0.0.0.0/0            198.19.0.0/24        tcp dpt:53
34601 2238K koolclash_dns  udp  --  *      *       0.0.0.0/0            198.19.0.0/24        udp dpt:53
54842 4430K koolclash  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           

 * iptables mangle 中 koolclash 链

 * iptables nat 中 koolclash 链
   90  4752 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set koolclash_white dst
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            192.168.100.100      tcp dpt:22
54752 4426K REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            redir ports 23456

* iptables mangle 中 koolclash_dns 链

 * iptables nat 中 koolclash_dns 链
34601 2238K DNAT       udp  --  *      *       0.0.0.0/0            198.19.0.0/24        udp dpt:53 to:192.168.100.100:23453
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            198.19.0.0/24        tcp dpt:53 to:192.168.100.100:23453

 * iptables nat 中 53 端口相关条目
4        0     0 koolclash_dns  tcp  --  *      *       0.0.0.0/0            198.19.0.0/24        tcp dpt:53
5    34601 2238K koolclash_dns  udp  --  *      *       0.0.0.0/0            198.19.0.0/24        udp dpt:53

---------------------- ipset 白名单 IP 列表 ------------------------
Name: koolclash_white
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 984
References: 1
Number of entries: 10
Members:
0.0.0.0/8
127.0.0.0/8
100.64.0.0/10
192.168.0.0/16
224.0.0.0/4
10.0.0.0/8
240.0.0.0/4
172.16.0.0/12
169.254.0.0/16
192.168.100.100

===================================================================

```
```

**Comment by BitionSong** [comment]
你是不是开通了2个dhcp服务？？关一个掉。

**Comment by NV3S** [comment]
> 你是不是开通了2个dhcp服务？？关一个掉。

并没有，旁路由的DHCP包括DHCPv6第一时间就关掉了。

**Comment by SukkaW** [comment]
路由器 LAN 口的 DNS 不应修改为 198.19.0.0/16 中的任何一个 IP。

**Comment by NV3S** [comment]
今天诊断了一下，是主路由ikuai开启了ipv6，导致子网支持ipv6的设备获取到了无法访问ipv6 dns。关闭该功能解决。
