### ISSUE TITLE
kooclash 页面刷新后页面显示不正常

### ISSUE THREAD

**Issue by ShadowLyin** [SukkaW/Koolshare-Clash#5]
![屏幕截图(1)](https://user-images.githubusercontent.com/20549332/54470276-d9457e00-47df-11e9-88ca-5fe0662be523.png)
koolshare版本：`Openwrt Koolshare mod V2.15 r6665-4758158`
koolclash版本：0.11.1

**Comment by SukkaW** [comment]
Fixed in version [0.11.2](https://github.com/SukkaW/Koolshare-Clash/releases/tag/0.11.2).
