### ISSUE TITLE
路由器自身流量不走Clash

### ISSUE THREAD

**Issue by yykhysn** [SukkaW/Koolshare-Clash#51]
嗨，

0.16.2 之后的版本，安装KoolClash的路由器，连接路由器的设备没有问题，但路由器自己发起的流量不走Clash。请问需要如何配置，才能让路由器路由器自身的流量也走Clash？

急切需要，盼早日回复。

**Comment by SukkaW** [comment]
KoolClash 自身流量不会经过 Clash。如果需要，请自行为相关应用程序配置 HTTP 代理和 SOCKS5 代理，引起的回环和导致的故障请君自理。

**Comment by yykhysn** [comment]
我是小白，不太明白，望苏卡大大详细指导下如何让 Koolshare LEDE 路由器自身的流量也被Clash代理。是要配置HTTP或SOCKS5代理吗，具体怎么做？需求是路由器自身的所有流量被代理，如Aria2、SmartDNS等应用所发起的。

谢谢！
