### ISSUE TITLE
[Bug Report]Google, Youtube 时断时连

### ISSUE THREAD

**Issue by twtjy2008** [SukkaW/Koolshare-Clash#54]
不管是最新的0.17.5版本还是0.16.2, 0.16.1都遇到这样一个问题: Google和Youtube经常出现打不开，ping不通的情况，手机谷歌商店无网络连接，但是不停地刷新一分钟左右之后可以连上Google和Youtube。过一两个小时之后又重复这个现象。当前网络是外网，关闭koolclash访问Google和Youtube正常。

在config.yml加入了:
DOMAIN-SUFFIX,google.com,DIRECT
DOMAIN-KEYWORD,google,DIRECT
DOMAIN,google.com,DIRECT
DOMAIN-SUFFIX,youtube.com,DIRECT
DOMAIN-KEYWORD,youtube,DIRECT
DOMAIN,youtube.com,DIRECT
GEOIP,US,DIRECT

在这样的设置下，依然出现Google和Youtube经常出现打不开，ping不通的情况，但是不停地刷新一分钟左右之后可以连上Google和Youtube的现象。

请问是我的使用方法不正确吗？如果不正确，应该如何设置才可以解决这个问题？谢谢！

**Comment by twtjy2008** [comment]
Log 里出现  dial tcp 216.58.194.174:443: i/o timeout

**Comment by eyaeya** [comment]
同有此问题！
