### ISSUE TITLE
[Bug Report]获取LAN IP时需要加一下判断

### ISSUE THREAD

**Issue by Mosney** [SukkaW/Koolshare-Clash#62]
**Bug 详情**

OpenWRT最新构建中network配置已使用CIDR代替传统子网掩码，会造成`uci get network.lan.addr `尾部多一个/24，koolclash获取LAN IP时需要加一下判断，否则会造成启动脚本中部分iptables设置无效，进而导致DNS无法重定向到clash

**屏幕截图**

![image](https://user-images.githubusercontent.com/22477230/67636633-b51d5400-f90d-11e9-81c6-ead050d39f44.png)
![image](https://user-images.githubusercontent.com/22477230/67637591-e2223480-f916-11e9-8bed-e707e604cee7.png)
![image](https://user-images.githubusercontent.com/22477230/67637531-6f18be00-f916-11e9-82d5-10585df53146.png)

**Comment by SukkaW** [comment]
![image](https://user-images.githubusercontent.com/40715044/68018105-41939200-fcd3-11e9-8fcd-2ce96d47c25c.png)

**Comment by SukkaW** [comment]
@Mosney 

Try this？

```bash
ubus call network.interface.lan status | jsonfilter -e '@["ipv4-address"][0].address'
```

If it is work I will use this instead.

**Comment by Mosney** [comment]
> @Mosney
> 
> Try this？
> 
> ```shell
> ubus call network.interface.lan status | jsonfilter -e '@["ipv4-address"][0].address'
> ```
> 
> If it is work I will use this instead.

It worked.
