### ISSUE TITLE
[Bug Report]修改lan的dhcp配置后无法访问clash面板

### ISSUE THREAD

**Issue by chuanzai** [SukkaW/Koolshare-Clash#69]
**Bug 详情**

用vi /etc/config/dhcp 后，无法打开clash面板

出现这个提示：请注意，修改该配置项并不会修改你的 Clash 配置文件，请确认修改后的外部控制地址和 Clash 配置文件内的地址一致，否则会导致 Dashboard 无法连接。

**你的操作**

**屏幕截图**

**调试信息**

```
```

**Comment by chuanzai** [comment]
在UI下面修改lan下面的dhcp，无法保存

**Comment by SukkaW** [comment]
请自行更改 Clash 监听 IP 和端口。
