### ISSUE TITLE
能否加入支持 SSR 的clashR 

### ISSUE THREAD

**Issue by wangruicacc0731** [SukkaW/Koolshare-Clash#75]
您好 很多机场都是 SSR 的订阅 ，想问问 如果向运用SSR 的订阅怎么处理呢，或者可否替换什么内核之类的

**Comment by SukkaW** [comment]
KoolClash 不是 KoolClashR。KoolClash 不会提供内置 ClashR Core 的版本、不会提供 SSR 支持。
如有使用 SSR 的需要，请自行向上游 Clash 提交 Feature Request。

**Comment by minGGeMG** [comment]
> 您好 很多机场都是 SSR 的订阅 ，想问问 如果向运用SSR 的订阅怎么处理呢，或者可否替换什么内核之类的

`https://docs.nameless13.com/shr`
