### ISSUE TITLE
dashboard显示不正常(已解决)

### ISSUE THREAD

**Issue by dhdgves** [SukkaW/Koolshare-Clash#94]
======================== KoolClash 调试工具 ========================
调试信息生成于 Fri Jul 10 2020 22:55:37 GMT+0800 (中国标准时间)
当前浏览器：Chrome 83
-------------------- Koolshare OpenWrt 基本信息 --------------------
固件版本： Openwrt Koolshare mod V2.31, r10822-50aa0525d1 by fw867
路由器 LAN IP：192.168.1.1
------------------------ KoolClash 基本信息 ------------------------
KoolClash 版本：0.17.9-beta
Clash 核心版本：Clash v0.16.0-14-g1948ea1 linux amd64 Fri 01 Nov 2019 02:02:20 PM UTC
KoolClash 当前状态：Clash 进程正在运行
用户指定 Clash 外部控制 Host：未改动
-------------------------- Clash 进程信息 --------------------------
20592 root      1080 S    /bin/sh /koolshare/scripts/koolclash_debug.sh 919612
20701 root      1080 S    /bin/sh /koolshare/scripts/koolclash_debug.sh 919612
30620 root      113m S    /koolshare/bin/clash -d /koolshare/koolclash/config/

------------------------ Clash 配置文件目录 ------------------------
-rwxrwxrwx    1 root     root        3.8M Jul 10 20:14 Country.mmdb
-rwxrwxrwx    1 root     root      597.7K Jul 10 22:12 config.yaml
-rwxrwxrwx    1 root     root         271 Jul 10 22:55 dns.yml
-rwxrwxrwx    1 root     root      597.4K Jul 10 20:15 origin.yml

------------------------ Clash 配置文件信息 ------------------------
Clash 透明代理端口：23456
Clash 是否允许局域网连接：true
Clash 外部控制监听地址：192.168.1.1:6170
--------------------- Clash 配置文件 DNS 配置 ----------------------
Clash DNS 是否启用：true
Clash DNS 解析 IPv6：false
Clash DNS 增强模式：fake-ip
Clash DNS 监听：0.0.0.0:23453
KoolClash 当前 DNS 模式：4
-------------------- KoolClash 自定义 DNS 配置 ---------------------
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - tls://dns.rubyfish.cn:853
    - 114.114.114.114
    - 223.5.5.5
    - https://dns.ngorkpriserver.top:4433/dns-query
  fallback:
    - 114.114.114.114
    - 139.196.219.53

------------------------- iptables 条目 ---------------------------
 * iptables mangle 中 Clash 相关条目

 * iptables nat 中 Clash 相关条目
    0     0 koolclash_dns  tcp  --  *      *       0.0.0.0/0            198.19.0.0/24        tcp dpt:53
    0     0 koolclash_dns  udp  --  *      *       0.0.0.0/0            198.19.0.0/24        udp dpt:53
 2196  123K koolclash  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0           

 * iptables mangle 中 koolclash 链

 * iptables nat 中 koolclash 链
  568 30128 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set koolclash_white dst
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            192.168.1.1          tcp dpt:22
 1627 92514 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            redir ports 23456

* iptables mangle 中 koolclash_dns 链

 * iptables nat 中 koolclash_dns 链
    0     0 DNAT       udp  --  *      *       0.0.0.0/0            198.19.0.0/24        udp dpt:53 to:192.168.1.1:23453
    0     0 DNAT       tcp  --  *      *       0.0.0.0/0            198.19.0.0/24        tcp dpt:53 to:192.168.1.1:23453

 * iptables nat 中 53 端口相关条目
4        0     0 koolclash_dns  tcp  --  *      *       0.0.0.0/0            198.19.0.0/24        tcp dpt:53
5        0     0 koolclash_dns  udp  --  *      *       0.0.0.0/0            198.19.0.0/24        udp dpt:53

---------------------- ipset 白名单 IP 列表 ------------------------
Name: koolclash_white
Type: hash:net
Revision: 6
Header: family inet hashsize 1024 maxelem 65536
Size in memory: 984
References: 1
Number of entries: 10
Members:
0.0.0.0/8
100.64.0.0/10
172.16.0.0/12
192.168.1.1
224.0.0.0/4
127.0.0.0/8
192.168.0.0/16
240.0.0.0/4
169.254.0.0/16
10.0.0.0/8

===================================================================

启动clash之后，使用dashboard进行链接。链接后发现dashboard的代理页面上是空白的。确认配置无误。有时候dashboard代理也可以正常显示，但是概率很小。

**Comment by yujqiao** [comment]
这是因为 [Clash 1.0 不再支持 Proxy 关键字配置](https://github.com/Dreamacro/clash/wiki/Breaking-Changes-in-1.0.0)，最近很多机场切换到新配置格式，KoolClash 内置的 Clash 版本较旧，不兼容。我手动更新二进制文件后解决。
